import type { Metadata } from "next";
import { Inter, Manrope, Alike_Angular } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { ToastContainer } from "react-toastify";
import { getUserFromToken } from "@/lib/verifyJWT";
import StoreProvider from "./StoreProvider";
import ScrollToTop from "@/components/ScrollToTop";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const alike = Alike_Angular({
  variable: "--font-alike",
  subsets: ["latin"],
  weight: "400",
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFromToken();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${alike.variable} ${manrope.variable}  antialiased`}>
        <StoreProvider>
          {/* //todo : add dark mode */}
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
            <Header user={user} />
            <main>{children}</main>
            <Footer />
            <ToastContainer position="bottom-left" autoClose={1000} />
            <ScrollToTop />
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
